import{a as h,S as g,i as u}from"./assets/vendor-5fa4b92b.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const v="live_T9LOtLYHAv6KhL2fGHosUVgFryfx9rB2J6x7kAgl8lqRbPsVFYQkCYagWcXOVTH2",y="https://api.thecatapi.com/v1",L="/breeds",S="/images/search",m=h.create({baseURL:y,headers:{"x-api-key":v}}),b=()=>m.get(L),R=t=>{const s=new URLSearchParams({breed_ids:t});return m.get(`${S}?${s}`)},f="Something went wrong!",p=document.querySelector(".breed-select"),n=document.querySelector(".loader"),d=document.querySelector(".cat-info"),i=t=>{t.classList.remove("visually-hidden")},l=t=>{t.classList.add("visually-hidden")};i(n);const I=t=>{const s=t.map(({id:o,name:c})=>({text:c,value:o}));s.unshift({text:"",placeholder:!0}),O.setData(s),l(n),i(p)},O=new g({select:p,settings:{placeholderText:"Select a breed:"},events:{afterChange:t=>{const s=t[0].value;s&&(l(d),i(n),R(s).then(({data:o})=>P(o[0])).catch(()=>{u.error({message:f,position:"topRight"})}))}}}),P=t=>{const{url:s,breeds:[{name:o,temperament:c,description:e}]}=t;d.innerHTML=`
    <img class="img" src="${s}" alt="${o}">
    <div class="cat-content">
      <div class="name">${o}</div>
      <div class="description">${e}</div>
      <div class="temperament">Temperament: ${c}</div>
    </div>
  `,l(n),i(d)};b().then(({data:t})=>I(t)).catch(()=>{u.error({message:f,position:"topRight"})});
//# sourceMappingURL=commonHelpers.js.map
