import{a as h,S as g,i as m}from"./assets/vendor-5fa4b92b.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&c(d)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const v="live_T9LOtLYHAv6KhL2fGHosUVgFryfx9rB2J6x7kAgl8lqRbPsVFYQkCYagWcXOVTH2",y="https://api.thecatapi.com/v1",L="/breeds",S="/images/search",f=h.create({baseURL:y,headers:{"x-api-key":v}}),b=()=>f.get(L),R=t=>{const s=new URLSearchParams({breed_ids:t});return f.get(`${S}?${s}`)},p="Something went wrong!",u=document.querySelector(".breed-select"),n=document.querySelector(".loader"),l=document.querySelector(".cat-info"),a=t=>{t.classList.remove("visually-hidden")},i=t=>{t.classList.add("visually-hidden")};i(u);a(n);const I=t=>{const s=t.map(({id:o,name:c})=>({text:c,value:o}));s.unshift({text:"",placeholder:!0}),O.setData(s),i(n),a(u)},O=new g({select:u,settings:{placeholderText:"Select a breed:"},events:{afterChange:t=>{const s=t[0].value;s&&(i(l),a(n),R(s).then(({data:o})=>P(o[0])).catch(()=>{i(n),m.error({message:p,position:"topRight"})}))}}}),P=t=>{const{url:s,breeds:[{name:o,temperament:c,description:e}]}=t;l.innerHTML=`
    <img class="img" src="${s}" alt="${o}">
    <div class="cat-content">
      <div class="name">${o}</div>
      <div class="description">${e}</div>
      <div class="temperament">Temperament: ${c}</div>
    </div>
  `,i(n),a(l)};b().then(({data:t})=>I(t)).catch(()=>{i(n),m.error({message:p,position:"topRight"})});
//# sourceMappingURL=commonHelpers.js.map
